import java.io.Serializable;

import javax.swing.JButton;
import javax.swing.JTextField;

// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/**
 * @author Sergio Perez
 * @author Zoe
 * @author Justin Lynch
 * @author Terrance Rose
 */
public class GameState implements Serializable {

	/**
	 * 1 if p1 turn, 2 if p2 turn
	 */
	int currPlayer_;
	/**
	 * Board that holds the state of the game board to give to clients
	 */
	Game game_;
	Board board_;
	boolean win_;// true if player win the game
	boolean startGame_;// true if player wants to start game
	boolean inProgress_;// true if player is in progress
	boolean gameInProgress_; // true if game is in progress
	String winner_ = "";// winner name
	String p1name_ = "";// black & player one's name
	String p2name_ = "";// white & player two's name
	String sender_ = "";// name of player sending message to server

	/**
	 * get the information of game
	 */
	public GameState () {

		board_ = GUI.getBoard();
		game_ = GUI.getGame();
		win_ = GUI.isWin();
		currPlayer_ = GUI.getGame().getCurrentPlayer();
		gameInProgress_ = GUI.isGameInProgress();
		p1name_ = GUI.p1name_;
		p2name_ = GUI.p2name_;

	}

};
