import java.io.Serializable;
import java.util.ArrayList;

// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/

/**
 * This class groups two players together in an online game and holds a list for
 * observers
 * 
 * @author Sergio Perez
 * @author Zoe
 * @author Justin Lynch
 * @author Terrance Rose
 */
public class OnlineGame implements Serializable {

	/**
	 * Holds name of players playing each other in this game
	 */
	private String[] playersPlaying_ = new String[2];

	/**
	 * Holds name of players observing this game.
	 */
	private ArrayList<String> observers_ = new ArrayList<String>();

	/**
	 * Game object which holds gameState of the OnlineGame
	 */
	private GameState state_ = new GameState();

	/**
	 * Constructor which takes name of both players
	 * 
	 * @param player1
	 * @param player2
	 */
	public OnlineGame ( String player1, String player2 ) {
		playersPlaying_[0] = player1;
		playersPlaying_[1] = player2;

	}

	/**
	 * Adds an observer to the observer list.
	 * 
	 * @param obs
	 *          name of observer to be added
	 */
	public void addObserver ( String obs ) {
		observers_.add(obs);

	}

	/**
	 * returns this OnlineGame's game state object
	 * 
	 * @return the gamestate obj
	 */
	public GameState getState () {
		return state_;
	}

	/**
	 * Returns players playing each other
	 * 
	 * @return the array containing both player's names
	 */
	public String[] getPlayers () {
		return playersPlaying_;
	}

	/**
	 * Sends message to both players and observers connected with this gamethread
	 * 
	 * @param message
	 *          to be send
	 */
	public void sendToAll ( Object message ) {

		System.out.println("send to all method gets called.");
		for ( ClientServicing temp : Server.threads ) {
			System.out.println(temp.getPlayerName() + " " + playersPlaying_[0]);
			if ( temp.getPlayerName().equals(playersPlaying_[0]) ) {
				temp.messageToClient(message);
			}
		}
		for ( ClientServicing temp : Server.threads ) {
			if ( temp.getPlayerName().equals(playersPlaying_[1]) ) {
				temp.messageToClient(message);
			}
		}

		for ( String name : observers_ ) {
			System.out
			    .println("this is the person in observer slot for game: " + name);
			for ( ClientServicing temp : Server.threads ) {
				if ( temp.getPlayerName().equals(name) ) {
					temp.messageToClient(message);
				}
			}
		}

	}

};
